### ISSUE TITLE
How to build the package in local iSeries host?

### ISSUE THREAD

**Issue by anson2416** [pierrickrouxel/rpg-logger#1]
HI, it is a nice job! Can you share how to build the package in iSereis? I saw a bash script but I am not sure how to run it with programmer profile (not admit profile). Thank you.

**Comment by pierrickrouxel** [comment]
Hello, thank you.

You can run build.sh with QSH if you have rights. If you can't, you can import sources in an SRCPF an run commands in build.sh manually.

**Comment by anson2416** [comment]
Hi, I am new in the free-format. I convern the H spec and testing program into fixed format. when i call the procedure LOG, hit error saying "pointer not set". but i surely passed 2  variable there. Any idea on this issue? and any change to convern this into fixed format?
